services:
  postgre:
    image: postgres:13.16
    restart: always
    environment:
      # As variáveis do .env serão usadas aqui
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      # A porta do HOST (sua máquina) agora é variável
      - "${DB_PORT}:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ecommerce:
    image: fabricioveronez/fake-shop
    restart: always
    environment:
      DB_HOST: postgre
      # As mesmas variáveis do .env são usadas aqui
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      # A porta interna da rede Docker continua a mesma
      DB_PORT: "5432"
      FLASK_APP: index.py
    ports:
      # A porta do HOST (sua máquina) agora é variável
      - "${APP_PORT}:5000"
    depends_on:
      postgre:
        condition: service_healthy
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 300 index:app

volumes:
  postgre_data:
